name: update items

on:
  workflow_dispatch:

jobs:
  prep_rust:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Restore cached rustserver
        id: cache-rustserver-restore
        uses: actions/cache/restore@v4
        with:
          path: rustserver
          key: rustserver-${{ runner.os }}-${{ github.event.repository.updated_at }}
          restore-keys: rustserver-${{ runner.os }}-

      - name: Update app
        run: |
          mkdir -p ${{ github.workspace }}/rustserver
          steamcmd +force_install_dir ${{ github.workspace }}/rustserver +login anonymous +app_update 258550 validate +quit

      - name: Cache rustserver
        id: cache-rustserver-save
        uses: actions/cache/save@v4
        with:
          path: rustserver
          key: rustserver-${{ runner.os }}-${{ github.event.repository.updated_at }}

      - name: Install oxide
        run: |
          ls -la
          curl -L https://umod.org/games/rust/download?tag=public -o oxide.zip
          unzip -o oxide.zip -d rustserver/

      - name: Install plugin
        run: |
          mkdir -p rustserver/oxide/plugins/
          cp RustItemDumper.cs rustserver/oxide/plugins/

      - name: Run RustItemDumper
        run: |
          cd rustserver
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)
          ln -s steamclient.so ./steamservice.so
          ls -la
          ./RustDedicated -batchmode +server.worldsize 1000
          ls -la oxide/data/*
