name: update items

on:
  workflow_dispatch:

jobs:
  prep_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Update app
        run: steamcmd +login anonymous +app_update 258550 validate +quit

      - name: Install oxide
        run: |
          ls -la
          curl -L https://umod.org/games/rust/download?tag=public -o oxide.zip
          unzip oxide.zip -d rustserver/

      - name: Install plugin
        run: |
          cp RustItemDumper.cs rustserver/oxide/plugins/